### ISSUE TITLE
Implement procedure for generating CSRs to replace self-signed certificates

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-docker#1]
When a node is first install, it uses self-signed certificates. These must be replaced by certificates issued by a commercial CA (apache) and signed by the ESGF CAs (Globus).

**Comment by pchengi** [comment]
@LucaCinquini , when a node is first installed, it uses self-signed certificates, not because we can't write a procedure to use certs issued by any other recognized CA. The real issues are these:
1. Key generation has to be done locally. If both key and certificate are generated remotely, the very basis of public key encryption is defeated, because technically, the secret key exists elsewhere.
2. CSRs can be automatically generated; this is very easy. Indeed, they are being done already. However, the process of signing of certificates should in principle never be automated, because that means there is no vetting of any kind. Also, there is no way to ensure that an entity doesn't obtain certificates for domains/hosts they don't control. 

For these reasons, you cannot do away with the self-signed certificates which are in place to allow standalone testing, till you obtain proper certificates.

**Comment by sashakames** [comment]
Revisiting this issue.  The new architecture will continue to require CSRs for all sites, now that we use keypair for SSL with filebeat/logstash for metrics, in addition to (optional but encouraged) Globus/gridFTP.   Its is not a difficult procedure to generate the private key and CSR. However either should be well documented and/or potentially automated in a playbook if that facilitates the procedure.
