### ISSUE TITLE
Make SLCS use the standard ESGF postgres and httpd

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-docker#19]
Who: Luca

Currently the SLCS server uses its own containers for the Django Postgres database, and NGINX for web content. We should instead consider using the standard ESGF Postgres database and Apache HTTPD.

**Comment by fgreg** [comment]
Just a couple comments.

SLCS could be integrated with the existing ESGF Postgres image. I'd recommend updating that image to create a new database exclusively for SLCS. All management of that database can be handled through the Django `makemigrations` command.

The HTTPD integration is a little more complicated I think. The reason I used nginx was simply because it was easy to get it up and running. The complicated part is how the static content is actually getting published. 

The Django application uses the `collectstatic` command to publish static content. This is very simple when the Django application co-hosted with the web server (nginx in this case. [See docs for details](https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/#serving-the-site-and-your-static-files-from-the-same-server)). However, to comply with Docker best practices, there should really only be 1 process running per container. So I was trying to avoid building a container that ran both the Django application and a web server (separating the two also improves flexibility as they can be scaled independently).

The solution I came up with relies on Docker volumes to publish the static files. The [docker-compose](https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/docker-compose.yml#L4) file defines the container volume that is later shared between the [Django app](https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/docker-compose.yml#L27) and the [nginx server](https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/docker-compose.yml#L41). Then the [settings.py](https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/settings.py#L178) sets the static root for the Django app and [docker-entrypoint](https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/docker-entrypoint.py#L256-L257) calls the `collectstatic` command.

So, in essence, the Django app thinks it's publishing files locally but because that static directory actually lives on the Docker volume that is shared with the nginx container (and nginx is configured to server that directory) it is actually publishing them on the nginx container.

This entire process should be able to be replicated with the existing HTTPD image but I wanted to explain the reasoning/process to better understand the work that would have to be done on the httpd image (mainly, it would need to serve a directory that gets mounted from a container volume).

It was also challenging to work around the file permission issues that arose. The best way I figured out was to make sure the nginx container started first, then the slcs-server container. This is because as part of the Docker file for slcs-server (sets the permissions correctly)[https://github.com/ESGF/esgf-docker/blob/84d95c627ab0ee18f10fa6ee906ba410d6dc6af7/slcs-server/Dockerfile#L74-L77] for the volume containing the static content.

Finally, just a note that Django recommends using [rsync](https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/#serving-static-files-from-a-dedicated-server) or hosting via a [CDN](https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/#serving-static-files-from-a-cloud-service-or-cdn) for publishing static content. Using one of those two methods may or may not make this whole process easier.

**Comment by LucaCinquini** [comment]
This is now obsolete since the SLCS container has been completely refactored by Matt.
